### ISSUE TITLE
What Postgres setup is required?

### ISSUE THREAD

**Issue by rajit** [KyleU/boilerplay#1]
In order to run and use this, what Postgres setup is necessary?

With nothing setup in Postgres, I get this:

```
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Line -> 362, File -> miscinit.c, SQLSTATE -> 28000, Routine -> InitializeSessionUserId, Message -> role "boilerplay" does not exist, Severity -> FATAL))
```

**Comment by kyleu** [comment]
You'll can either change the application.conf to point to an existing user and empty database, or create a 'boilerplay' role and database The startup routine will build the tables for you.

**Comment by rajit** [comment]
Cool, very simple!
My little suggestion: add a little note to the README.md to go through `conf/application.conf` to check for settings. From what I can see the settings to update are:
- Postgres login information
- SMTP server & credentials
- Twitter credentials
- Facebook credentials
- Google credentials

For Postgres, the minimum required is:

```
$ CREATE ROLE boilerplay WITH LOGIN PASSWORD 'password';
$ CREATE DATABASE boilerplay;
$ GRANT ALL PRIVILEGES ON DATABASE boilerplay TO boilerplay;
```

For SMTP, signing up to Gmail will do it.

For Twitter, visit https://apps.twitter.com/ and create a new app.

For Facebook, visit https://developers.facebook.com/products/ads/? and choose My Apps > Add a new app

For Google, visit https://console.developers.google.com/, create a project and create credentials for it.

For whatever reason, after auto-creating the tables I needed to restart the application before it could access those tables that it had created.

This is the kind of message I was getting:

```
[error] 09:06:54.371 b.Database: Error [GenericDatabaseException] encountered while executing statement [Insert].
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Position -> 26, Line -> 986, File -> parse_relation.c, SQLSTATE -> 42P01, Routine -> parserOpenTable, Message -> relation "requests" does not exist, Severity -> ERROR))
    at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:169) ~[postgresql-async_2.11-0.2.16.jar:0.2.16]
    at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:151) ~[postgresql-async_2.11-0.2.16.jar:0.2.16]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_51]
```

**Comment by kyleu** [comment]
Done, thanks for the suggestion!

**Comment by kyleu** [comment]
Readme has been updated with your suggestions - thanks again, @rajit !
