### ISSUE TITLE
Exception viewing application.log

### ISSUE THREAD

**Issue by intracer** [KyleU/boilerplay#12]
application.log log content:
2015-07-31 12:03:16,423 [INFO] from play.api.libs.concurrent.ActorSystemProvider in pool-4-thread-3 - Starting application default Akka system: application
2015-07-31 12:03:16,534 [INFO] from play.core.server.NettyServer in pool-4-thread-3 - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

exception log:
! @6n21lo10d - Internal server error, for (GET) [/admin/logs/application.log] ->
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalStateException: Unhandled line [0] with no pending log: [(2015-07-31 12:03:16,423 [INFO] from play.api.libs.concurrent.ActorSystemProvider in pool-4-thread-3 - Starting application default Akka system: application,0)].]]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
at utils.play.PlayGlobalSettings$.onError(PlayGlobalSettings.scala:47) [classes/:na]
at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.2.jar:2.4.2]
at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.2.jar:2.4.2]
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.7.jar:na]
at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
at scala.util.Failure.recover(Try.scala:216) [scala-library-2.11.7.jar:na]
at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.2.jar:2.4.2]
at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.2.jar:2.4.2]
at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.7.jar:na]
at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.7.jar:na]
at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.7.jar:na]
at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.7.jar:na]
at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.11.7.jar:na]
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [akka-actor_2.11-2.3.11.jar:na]
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [akka-actor_2.11-2.3.11.jar:na]
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library-2.11.7.jar:na]
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [akka-actor_2.11-2.3.11.jar:na]
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: java.lang.IllegalStateException: Unhandled line [0] with no pending log: [(2015-07-31 12:03:16,423 [INFO] from play.api.libs.concurrent.ActorSystemProvider in pool-4-thread-3 - Starting application default Akka system: application,0)].
at services.audit.LogService$$anonfun$getLogs$1.apply(LogService.scala:35) ~[classes/:na]
at services.audit.LogService$$anonfun$getLogs$1.apply(LogService.scala:25) ~[classes/:na]
at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[scala-library-2.11.7.jar:na]
at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[scala-library-2.11.7.jar:na]
at services.audit.LogService$.getLogs(LogService.scala:25) ~[classes/:na]
at controllers.admin.LogController$$anonfun$view$1.apply(LogController.scala:18) ~[classes/:na]
at controllers.admin.LogController$$anonfun$view$1.apply(LogController.scala:17) ~[classes/:na]
at controllers.BaseController$$anonfun$withAdminSession$1$$anonfun$apply$1.apply(BaseController.scala:27) ~[classes/:na]
at controllers.BaseController$$anonfun$withAdminSession$1$$anonfun$apply$1.apply(BaseController.scala:24) ~[classes/:na]
at nl.grons.metrics.scala.FutureMetrics$class.timing(FutureMetrics.scala:97) ~[metrics-scala_2.11-3.5.1.jar:3.5.1]
at controllers.BaseController.timing(BaseController.scala:20) ~[classes/:na]
at controllers.BaseController$$anonfun$withAdminSession$1.apply(BaseController.scala:24) ~[classes/:na]
at controllers.BaseController$$anonfun$withAdminSession$1.apply(BaseController.scala:23) ~[classes/:na]
at com.mohiva.play.silhouette.api.Silhouette$SecuredActionBuilder$$anonfun$1.apply(Silhouette.scala:445) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
at com.mohiva.play.silhouette.api.Silhouette$SecuredActionBuilder$$anonfun$1.apply(Silhouette.scala:445) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
at com.mohiva.play.silhouette.api.Silhouette$SecuredRequestHandlerBuilder$$anonfun$invokeBlock$1$$anonfun$apply$8.apply(Silhouette.scala:369) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
at com.mohiva.play.silhouette.api.Silhouette$SecuredRequestHandlerBuilder$$anonfun$invokeBlock$1$$anonfun$apply$8.apply(Silhouette.scala:369) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
at com.mohiva.play.silhouette.api.Silhouette$RequestHandlerBuilder$class.handleInitializedAuthenticator(Silhouette.scala:276) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
at com.mohiva.play.silhouette.api.Silhouette$RequestHandlerBuilder$class.handleBlock(Silhouette.scala:227) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
at com.mohiva.play.silhouette.api.Silhouette$SecuredRequestHandlerBuilder.handleBlock(Silhouette.scala:353) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
at com.mohiva.play.silhouette.api.Silhouette$SecuredRequestHandlerBuilder$$anonfun$invokeBlock$1.apply(Silhouette.scala:369) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
at com.mohiva.play.silhouette.api.Silhouette$SecuredRequestHandlerBuilder$$anonfun$invokeBlock$1.apply(Silhouette.scala:365) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library-2.11.7.jar:na]
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library-2.11.7.jar:na]
... 13 common frames omitted

**Comment by kyleu** [comment]
Did you change the logging format for boilerplay.log? It normally starts with [LEVEL].
