### ISSUE TITLE
Error injecting constructor: Encoder doesn't match Sender: JSON THRIFT

### ISSUE THREAD

**Issue by abrighton** [KyleU/boilerplay#26]
Thanks for putting up this great example!

I get this error when running the application (on Fedora 26):

```
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Encoder doesn't match Sender: JSON THRIFT
  at util.tracing.TracingService.<init>(TracingService.scala:16)
  at util.tracing.TracingService.class(TracingService.scala:16)
  while locating util.tracing.TracingService
    for the 5th parameter of util.web.ErrorHandler.<init>(ErrorHandler.scala:15)
  while locating util.web.ErrorHandler
  while locating play.api.http.HttpErrorHandler
    for the 1st parameter of util.web.RequestHandler.<init>(RequestHandler.scala:14)
  while locating util.web.RequestHandler
  while locating play.api.http.HttpRequestHandler
    for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:236)
  at play.api.DefaultApplication.class(Application.scala:235)
  while locating play.api.DefaultApplication
  while locating play.api.Application
Caused by: java.lang.IllegalArgumentException: Encoder doesn't match Sender: JSON THRIFT
	at zipkin.reporter.AsyncReporter$Builder.build(AsyncReporter.java:178)
	at zipkin.reporter.AsyncReporter.v2(AsyncReporter.java:52)
	at util.tracing.TracingService.<init>(TracingService.scala:33)
	at util.tracing.TracingService$$FastClassByGuice$$52407dcb.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
```
Any idea what could be the cause?

**Comment by kyleu** [comment]
Sorry for the delay, this is corrected now.
