### ISSUE TITLE
unresolved dependencies com.atlassian.jwt#jwt-core;1.2.4

### ISSUE THREAD

**Issue by simerplaha** [KyleU/boilerplay#3]
I'm getting unresolved dependencies com.atlassian.jwt#jwt-core;1.2.4. I've tried adding the following two repositories into plugin.sbt file with the other resolvers after reading [this](https://github.com/mohiva/play-silhouette-seed/issues/20#issuecomment-75367376) post but it's still a problem. 

```
resolvers += "scalaz-bintray" at "https://dl.bintray.com/scalaz/releases"
resolvers += "Atlassian Releases" at "https://maven.atlassian.com/public/"
```

```
[info] Resolving com.atlassian.jwt#jwt-core;1.2.4 ...
[warn]  module not found: com.atlassian.jwt#jwt-core;1.2.4
[warn] ==== local: tried
[warn]   /Users/me/.ivy2/local/com.atlassian.jwt/jwt-core/1.2.4/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /doesnotexist/repository/com.atlassian.jwt/jwt-core/1.2.4/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   /usr/local/Cellar/typesafe-activator/1.3.2/libexec/repository/com.atlassian.jwt/jwt-core/1.2.4/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/atlassian/jwt/jwt-core/1.2.4/jwt-core-1.2.4.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/atlassian/jwt/jwt-core/1.2.4/jwt-core-1.2.4.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.atlassian.jwt/jwt-core/1.2.4/ivys/ivy.xml
[info] Resolving com.atlassian.jwt#jwt-api;1.2.4 ...
[warn]  module not found: com.atlassian.jwt#jwt-api;1.2.4
[warn] ==== local: tried
[warn]   /Users/me/.ivy2/local/com.atlassian.jwt/jwt-api/1.2.4/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /doesnotexist/repository/com.atlassian.jwt/jwt-api/1.2.4/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   /usr/local/Cellar/typesafe-activator/1.3.2/libexec/repository/com.atlassian.jwt/jwt-api/1.2.4/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/atlassian/jwt/jwt-api/1.2.4/jwt-api-1.2.4.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/atlassian/jwt/jwt-api/1.2.4/jwt-api-1.2.4.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.atlassian.jwt/jwt-api/1.2.4/ivys/ivy.xml
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.atlassian.jwt#jwt-core;1.2.4: not found
[warn]  :: com.atlassian.jwt#jwt-api;1.2.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]      com.atlassian.jwt:jwt-core:1.2.4
[warn]        +- com.mohiva:play-silhouette_2.11:3.0.0 (/Users/me/IdeaProjects/boilerplay-master/project/Server.scala#L44)
[warn]        +- boilerplay:boilerplay_2.11:0.1-SNAPSHOT
[warn]      com.atlassian.jwt:jwt-api:1.2.4
[warn]        +- com.mohiva:play-silhouette_2.11:3.0.0 (/Users/me/IdeaProjects/boilerplay-master/project/Server.scala#L44)
[warn]        +- boilerplay:boilerplay_2.11:0.1-SNAPSHOT
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
sbt.ResolveException: unresolved dependency: com.atlassian.jwt#jwt-core;1.2.4: not found
unresolved dependency: com.atlassian.jwt#jwt-api;1.2.4: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:165)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (boilerplay/*:update) sbt.ResolveException: unresolved dependency: com.atlassian.jwt#jwt-core;1.2.4: not found
[error] unresolved dependency: com.atlassian.jwt#jwt-api;1.2.4: not found

```

**Comment by kyleu** [comment]
I just updated the resolvers, and tested with a fresh Ivy cache (200MB downloaded!). You should be good now.

**Comment by naveensky** [comment]
Hi, 

I am still getting this error on my build servers. This has been happening since yesterday and is still continuing to get error about JWT missing dependency.

Is there a workaround for now ?

**Comment by kyleu** [comment]
Hmm, I'm able to resolve it with an empty ivy cache. It's a Silhouette dependency, and I applied the fix they suggested. Can you send your resolve log? It should search several repos.

**Comment by naveensky** [comment]
Here we go 

```
[info] Resolving com.atlassian.jwt#jwt-core;1.2.4 ...
[warn]  module not found: com.atlassian.jwt#jwt-core;1.2.4
[warn] ==== local: tried
[warn]   /Users/naveen/.ivy2/local/com.atlassian.jwt/jwt-core/1.2.4/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /Users/naveen/libs/activator/repository/com.atlassian.jwt/jwt-core/1.2.4/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   /Users/naveen/libs/activator/repository/com.atlassian.jwt/jwt-core/1.2.4/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/atlassian/jwt/jwt-core/1.2.4/jwt-core-1.2.4.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/atlassian/jwt/jwt-core/1.2.4/jwt-core-1.2.4.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.atlassian.jwt/jwt-core/1.2.4/ivys/ivy.xml
[info] Resolving com.atlassian.jwt#jwt-api;1.2.4 ...
[warn]  module not found: com.atlassian.jwt#jwt-api;1.2.4
[warn] ==== local: tried
[warn]   /Users/naveen/.ivy2/local/com.atlassian.jwt/jwt-api/1.2.4/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /Users/naveen/libs/activator/repository/com.atlassian.jwt/jwt-api/1.2.4/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   /Users/naveen/libs/activator/repository/com.atlassian.jwt/jwt-api/1.2.4/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/atlassian/jwt/jwt-api/1.2.4/jwt-api-1.2.4.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/atlassian/jwt/jwt-api/1.2.4/jwt-api-1.2.4.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.atlassian.jwt/jwt-api/1.2.4/ivys/ivy.xml
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.atlassian.jwt#jwt-core;1.2.4: not found
[warn]  :: com.atlassian.jwt#jwt-api;1.2.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]      com.atlassian.jwt:jwt-core:1.2.4
[warn]        +- com.mohiva:play-silhouette_2.11:3.0.0 (/Volumes/Data/Code/sunkalp/web/trunk/build.sbt#L9-30)
[warn]        +- sunkalp-web:sunkalp-web_2.11:1.0-SNAPSHOT
[warn]      com.atlassian.jwt:jwt-api:1.2.4
[warn]        +- com.mohiva:play-silhouette_2.11:3.0.0 (/Volumes/Data/Code/sunkalp/web/trunk/build.sbt#L9-30)
[warn]        +- sunkalp-web:sunkalp-web_2.11:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.atlassian.jwt#jwt-core;1.2.4: not found
unresolved dependency: com.atlassian.jwt#jwt-api;1.2.4: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:165)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.atlassian.jwt#jwt-core;1.2.4: not found
[error] unresolved dependency: com.atlassian.jwt#jwt-api;1.2.4: not found
[error] Total time: 13 s, completed 31 Jul, 2015 3:37:10 AM
```

**Comment by kyleu** [comment]
Yeah, it's not using the JCenter repo. Assuming your code is up to date,
I'm not sure what to suggest. Do you see the JCenter repo in
project/Server.scala?

**Comment by naveensky** [comment]
@KyleU - Thanks, It seems I was missing the JCentre Repo in my server file. Strangely enough, it was working good till yesterday,

Anyways, thanks for the pointer :)

**Comment by kyleu** [comment]
Glad to hear it's working for you!

**Comment by jerrykurian** [comment]
Hi Naveen
What change did you do in the Server.scala to fix this? I am getting the same issue.

Thanks

**Comment by naveensky** [comment]
@jerrykurian - I added the following line to my build.sbt

```
resolvers += Resolver.jcenterRepo
```

Let me know if this helps?
