### ISSUE TITLE
Console is flooded with Insert errors

### ISSUE THREAD

**Issue by intracer** [KyleU/boilerplay#9]
[error] 20:06:49.873 b.Database: Error [GenericDatabaseException] encountered while executing statement [Insert].
com.github.mauricio.async.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=Map(Position -> 26, Line -> 984, File -> parse_relation.c, SQLSTATE -> 42P01, Routine -> parserOpenTable, Message -> relation "requests" does not exist, Severity -> ERROR))
    at com.github.mauricio.async.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.scala:169) ~[postgresql-async_2.11-0.2.16.jar:0.2.16]
    at com.github.mauricio.async.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.scala:151) ~[postgresql-async_2.11-0.2.16.jar:0.2.16]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_45]

**Comment by intracer** [comment]
Full log
https://drive.google.com/file/d/0B9q2GDHgr9kZQ2I5OHBpSUpMUG8/view?usp=sharing

**Comment by kyleu** [comment]
Is the requests table actually missing? Does the console show an error creating the table on startup?

**Comment by kyleu** [comment]
OK, thank you for the log. It looks like the requests table is created before the users table, which it depends on. I'll check in a fix tonight, but for now you can just restart the server and the requests table will be created.

**Comment by intracer** [comment]
Yes, restarting helped.

Creation log is

[INFO] 2015-07-30 19:23:18,784 from boilerplay.PlayGlobalSettings in New I/O worker #4 
Request from [127.0.0.1]: GET /

[INFO] 2015-07-30 19:23:18,975 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-9 
Creating missing table [oauth1_info].

[INFO] 2015-07-30 19:23:18,975 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-5 
Creating missing table [oauth2_info].

[INFO] 2015-07-30 19:23:18,977 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-4 
Creating missing table [users].

[INFO] 2015-07-30 19:23:18,977 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-6 
Creating missing table [user_feedback].

[INFO] 2015-07-30 19:23:18,978 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-2 
Creating missing table [password_info].

[INFO] 2015-07-30 19:23:18,978 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-7 
Creating missing table [user_profiles].

[INFO] 2015-07-30 19:23:18,986 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-8 
Creating missing table [session_info].

[INFO] 2015-07-30 19:23:18,986 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-4 
Creating missing table [requests].

[INFO] 2015-07-30 19:23:18,986 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-5 
Creating missing table [openid_info].

[INFO] 2015-07-30 19:23:18,986 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-6 
Creating missing table [client_trace].

[INFO] 2015-07-30 19:23:18,987 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-9 
Creating missing table [adhoc_queries].

[INFO] 2015-07-30 19:23:18,990 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-4 
Creating missing table [user_feedback_notes].

[INFO] 2015-07-30 19:23:18,991 from boilerplay.Schema in boilerplay-akka.actor.default-dispatcher-5 
Creating missing table [daily_metrics].

**Comment by kyleu** [comment]
Thanks for the input, @intracer - I'm working on the first-start fix now.

**Comment by intracer** [comment]
You did not fix the issue yet, but already closed it? Documenting it  https://github.com/KyleU/boilerplay/commit/2d3bef3fe534e4a8eb669a4839bacca54d5045fd  is not quite a fixing.

**Comment by kyleu** [comment]
Reopening until I have a fix in place.

**Comment by kyleu** [comment]
Resolved with a foldLeft instead of Future.sequence. Thanks for the report!
